# Generated by Django 6.0.2 on 2026-03-02 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Objective",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.TextField(db_comment="Название", verbose_name="Название")),
                ("description", models.TextField(db_comment="Описание", verbose_name="Описание")),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4)],
                        db_comment="Сложность",
                        verbose_name="Сложность",
                    ),
                ),
                (
                    "kind",
                    models.TextField(
                        choices=[("ACHIEVEMENT", "Ачивка"), ("QUEST", "Квест")],
                        db_comment="Вид цели",
                        verbose_name="Вид цели",
                    ),
                ),
                (
                    "target_value",
                    models.IntegerField(
                        db_comment="Необходимо для выполнения",
                        verbose_name="Необходимо для выполнения",
                    ),
                ),
                (
                    "current_value",
                    models.IntegerField(
                        db_comment="Текущее значение", verbose_name="Текущее значение"
                    ),
                ),
                ("completed_at", models.DateTimeField(null=True)),
                ("archived_at", models.DateTimeField(null=True)),
                (
                    "parent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="objectives.objective"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "objectives",
                "db_table_comment": "Цели",
            },
        ),
    ]
