# Generated by Django 6.0.2 on 2026-03-02 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("objectives", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objective",
            name="parent_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="objectives.objective"
            ),
        ),
    ]
