# Generated by Django 6.0.2 on 2026-03-02 04:51
from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("objectives", "0002_alter_objective_parent_id"),
    ]

    operations: ClassVar = [
        migrations.RenameField(
            model_name="objective",
            old_name="user_id",
            new_name="user",
        ),
    ]
