# Generated by Django 6.0.2 on 2026-03-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0002_alter_objective_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objective',
            old_name='user_id',
            new_name='user',
        ),
    ]
