# Generated by Django 6.0.2 on 2026-03-05 05:42
from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("objectives", "0003_rename_user_id_objective_user"),
    ]

    operations: ClassVar = [
        migrations.AlterModelOptions(
            name="objective",
            options={"verbose_name": "Цель", "verbose_name_plural": "Цели"},
        ),
        migrations.RenameField(
            model_name="objective",
            old_name="parent_id",
            new_name="parent",
        ),
    ]
